/* =====================================================
   POINTS HISTORY
===================================================== */
(function(){
  function historyAvatar(name){if(typeof cuteAvatarSvg==="function")return cuteAvatarSvg(name);if(typeof getAvatar==="function")return getAvatar(name);return "👤"}
  function formatDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}
  function formatTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}
  function ensureModal(){let m=document.getElementById("historyOverlay");if(m)return m;m=document.createElement("div");m.id="historyOverlay";m.className="overlay history-overlay";m.innerHTML=`<div class="history-modal" role="dialog" aria-modal="true" aria-labelledby="historyTitle"><div class="history-header"><div><div class="history-kicker">Family Rewards</div><h2 id="historyTitle">Points History</h2><p id="historySubtitle">Your recent points activity</p></div><button class="history-close" type="button">×</button></div><div id="historyContent" class="history-content"></div><div id="historyParentActions" class="history-parent-actions" style="display:none"><button id="clearHistoryButton" class="clear-history-button" type="button">Clear History</button></div></div>`;document.body.appendChild(m);m.querySelector(".history-close").onclick=closeHistory;m.onclick=e=>{if(e.target===m)closeHistory()};m.querySelector("#clearHistoryButton").onclick=clearAllHistory;return m}
  function closeHistory(){const m=document.getElementById("historyOverlay");if(m)m.style.display="none"}
  function escapeHistory(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
  async function showHistory(){if(!window.currentProfile||!window.supabaseClient)return;const m=ensureModal(),c=m.querySelector("#historyContent"),sub=m.querySelector("#historySubtitle"),actions=m.querySelector("#historyParentActions"),parent=String(window.currentProfile.role||"").toLowerCase()==="parent";c.innerHTML='<div class="history-loading"><span class="history-spinner"></span>Loading history...</div>';sub.textContent=parent?"Recent activity from the whole family":"Your recent points activity";actions.style.display=parent?"flex":"none";m.style.display="flex";try{let q=window.supabaseClient.from("points_history").select("id,user_id,amount,type,description,created_at").order("created_at",{ascending:false}).limit(50);if(!parent)q=q.eq("user_id",window.currentProfile.id);const r=await q;if(r.error)throw r.error;const rows=r.data||[];if(!rows.length){c.innerHTML='<div class="history-empty"><div class="history-empty-icon">✨</div><strong>No points activity yet</strong><p>Points you receive or spend will appear here.</p></div>';return}const map=new Map((window.profiles||[]).map(p=>[Number(p.id),p]));c.innerHTML=rows.map(item=>{const p=map.get(Number(item.user_id)),name=p?.name||(Number(item.user_id)===Number(window.currentProfile.id)?window.currentProfile.name:"Family member"),amount=Number(item.amount||0),positive=amount>0,type=String(item.type||"").toLowerCase(),icon=type==="redemption"?"🛒":positive?"⭐":"➖",title=type==="redemption"?"Reward Redeemed":positive?"Points Added":"Points Removed",txt=`${amount>0?"+":"−"}${Math.abs(amount).toLocaleString()}`;return `<div class="history-item"><div class="history-item-avatar">${historyAvatar(name)}</div><div class="history-item-main"><div class="history-item-title">${icon} ${escapeHistory(title)}</div><div class="history-item-meta">${parent?`<strong>${escapeHistory(name)}</strong> · `:""}${escapeHistory(item.description||"Points activity")} · ${formatDate(item.created_at)} · ${formatTime(item.created_at)}</div></div><div class="history-item-cost ${positive?"history-positive":"history-negative"}">${txt}<small>pts</small></div></div>`}).join("")}catch(e){console.error("Points history error:",e);c.innerHTML=`<div class="history-empty"><div class="history-empty-icon">⚠️</div><strong>Unable to load history</strong><p>${escapeHistory(e.message||"Please try again.")}</p></div>`}}
  async function clearAllHistory(){if(!window.currentProfile||String(window.currentProfile.role||"").toLowerCase()!=="parent")return;if(!window.confirm("Clear all family history? This will permanently delete all points and redemption history for everyone."))return;const b=document.getElementById("clearHistoryButton");if(b){b.disabled=true;b.textContent="Clearing..."}try{const h=await window.supabaseClient.from("points_history").delete().gte("id",0);if(h.error)throw new Error(`Points history: ${h.error.message}`);const r=await window.supabaseClient.from("redemptions").delete().gte("id",0);if(r.error)throw new Error(`Redemption history: ${r.error.message}`);const c=document.getElementById("historyContent");if(c)c.innerHTML='<div class="history-empty"><div class="history-empty-icon">✨</div><strong>History cleared</strong><p>All family points and redemption history has been deleted.</p></div>';if(typeof showToast==="function")showToast("All family history cleared.")}catch(e){console.error("Clear history error:",e);if(typeof showToast==="function")showToast(`Unable to clear history: ${e.message||e}`);else window.alert(`Unable to clear history: ${e.message||e}`)}finally{if(b){b.disabled=false;b.textContent="Clear History"}}}
  const style=document.createElement("style");style.textContent=`.history-parent-actions{justify-content:flex-end;margin-top:16px;padding-top:14px;border-top:1px solid #eceee9}.clear-history-button{border:1px solid #efc9c5;background:#fff7f6;color:#a04c43;border-radius:10px;padding:9px 14px;font:600 12px inherit;cursor:pointer}.clear-history-button:hover{background:#fcecea}.clear-history-button:disabled{opacity:.6;cursor:wait}`;document.head.appendChild(style);
  window.showHistory=showHistory;window.closeHistory=closeHistory;
})();
